version: '3.8'

services:
  spacetimedb:
    image: clockworklabs/spacetimedb:latest
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/backend
    working_dir: /app/backend
    command: spacetime dev --listen-addr 0.0.0.0:3000
    environment:
      - RUST_LOG=info

  frontend:
    image: node:20-alpine
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=development
    depends_on:
      - spacetimedb